### PR TITLE
Distinguish between Intel and ARM to supply native binary

### PR DESCRIPTION
**Pull request by klochowicz**
Download native binaries for the platform the user is running.

### CODE REVIEW

**Comment by klochowicz** [comment]
works for intel, can anyone test it with m1 mac with the following steps?

1. `brew tap itchysats/itchysats`
2. `cd /usr/local/Homebrew/Library/Taps/itchysats/homebrew-itchysats`
3. `git checkout `add-itchysats-cask` (to change to this PR branch)
4. `brew install itchysats`

....it should have installed the ARM version :)

**Comment by bonomat** [comment]
It's asking me to login ?

image

**Comment by klochowicz** [comment]
> It's asking me to login ?
> 
> image

thanks for the feedback - something's wrong with homebrew, will create an issue on their repo.

does the same happen with this?
```
brew tap itchysats/homebrew https://github.com/itchysats/homebrew
```

**Comment by klochowicz** [comment]
> It's asking me to login ?
> 
> image

I fixed the issue - turns out I had to rename the repo on github to support the convention better.
`brew tap itchysats/itchysats` should work now. (note: the instructions had to be adjusted a bit)

**Comment by bonomat** [comment]
> `brew tap itchysats/homebrew https://github.com/itchysats/homebrew`

this worked. 

image

I was also able to start it on my M1 :)

**Comment by klochowicz** [comment]
> > `brew tap itchysats/homebrew https://github.com/itchysats/homebrew`
> 
> this worked.
> 
> image
> 
> I was also able to start it on my M1 :)

awesome, would you mind approving the PR then? :D

**Review by bonomat — APPROVED** [review]

**Pull request merged**
